# Generated by Django 2.0 on 2020-01-10 18:08

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('edad', models.IntegerField(validators=[authentication.models.validator_edad])),
                ('region', models.CharField(choices=[('Galicia', 'Galicia'), ('Principado de Asturias', 'Principado de Asturias'), ('Cantabria', 'Cantabria'), ('País Vasco', 'Pais Vasco'), ('Navarra', 'Navarra'), ('Aragon', 'Aragón'), ('Catalunya', 'Cataluña'), ('Castilla y Leon', 'Castilla y León'), ('La Rioja', 'La Rioja'), ('Comunidad de Madrid', 'Comunidad de Madrid'), ('Extremadura', 'Extremadura'), ('Castilla La Mancha', 'Castilla La Mancha'), ('Comunidad Valenciana', 'Comunidad Valenciana'), ('Islas Baleares', 'Islas Baleares'), ('Andalucia', 'Andalucía'), ('Region de Murcia', 'Región de Murcia'), ('Islas Canarias', 'Islas Canarias')], max_length=50)),
                ('profesion', models.TextField(max_length=50)),
                ('estudios', models.TextField(max_length=50)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
