# Generated by Django 2.0 on 2020-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Prefiero no decirlo', 'Prefiero no decirlo')], default='Prefiero no decirlo', max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='estudios',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='profesion',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='region',
            field=models.CharField(blank=True, choices=[('Galicia', 'Galicia'), ('Principado de Asturias', 'Principado de Asturias'), ('Cantabria', 'Cantabria'), ('País Vasco', 'Pais Vasco'), ('Navarra', 'Navarra'), ('Aragon', 'Aragón'), ('Catalunya', 'Cataluña'), ('Castilla y Leon', 'Castilla y León'), ('La Rioja', 'La Rioja'), ('Comunidad de Madrid', 'Comunidad de Madrid'), ('Extremadura', 'Extremadura'), ('Castilla La Mancha', 'Castilla La Mancha'), ('Comunidad Valenciana', 'Comunidad Valenciana'), ('Islas Baleares', 'Islas Baleares'), ('Andalucia', 'Andalucía'), ('Region de Murcia', 'Región de Murcia'), ('Islas Canarias', 'Islas Canarias')], max_length=50),
        ),
    ]
