# Generated by Django 2.2.6 on 2020-01-17 18:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateField()),
                ('backup_data', base.models.BigBigField()),
            ],
        ),
    ]
