# Generated by Django 2.0 on 2020-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted',
            field=models.DateTimeField(),
        ),
    ]
