# Generated by Django 2.0 on 2020-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200110_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter_age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_city',
            field=models.TextField(default='Sevilla'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_sex',
            field=models.TextField(default='Hombre'),
        ),
    ]
