# Generated by Django 2.0 on 2020-01-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='backup_data',
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
