# Generated by Django 2.0 on 2020-01-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200121_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='backup_date',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='backup_name',
        ),
    ]
